py# Streamlit Wesbite project

import streamlit as st
import time


def page():
    return st.set_page_config(
         page_title="My First Web App",
         page_icon=":shark:",
         layout="wide",
         initial_sidebar_state="expanded",
         menu_items={
             'Get Help': 'https://www.extremelycoolapp.com/help',
             'Report a bug': "https://www.extremelycoolapp.com/bug",
             'About': "# This is a header. This is an *extremely* cool app!"

         }
     )

page()


with st.container():
    col1, col2, col3 = st.columns([1,6,1])
    with col2:
        st.header(' Hi, I am Sahil Bhatt. :wave: ' )
        st.markdown("<h4 style='text-align: left; color: white;'>Python Master in Making </h4>", unsafe_allow_html=True)


        st.write('''
        
       Welcome to the world of Python programming! Python is a high-level, interpreted programming language that is widely used for web development, scientific computing, data analysis, artificial intelligence, and more. With its simple syntax, powerful libraries, and supportive community, Python is a great choice for anyone looking to learn to code. To master Python quickly, it's important to be consistent with your learning, set achievable goals, and practice by building projects. Surround yourself with resources such as online tutorials, forums, and other learners to help keep you motivated and on track. Happy coding!
        
       Additionally, the efforts you put in to learn Python will greatly impact your success in mastering it. Consistent daily practice and exposure to new concepts and challenges will help solidify your understanding and improve your skills. Try to actively seek out opportunities to apply what you have learned to real-world problems. Whether it's contributing to open-source projects, working on personal projects, or participating in coding competitions, putting your knowledge into action will help you understand and retain the information better. Lastly, don't be afraid to ask for help when you need it. The Python community is large and friendly, and there is always someone willing to assist you on your learning journey. Good luck and keep up the great work! 
        ''')

    with col3:
        st.markdown('#')
        st.markdown('#')
        st.markdown('#')
        st.markdown('#')



        st.write(''' :point_left: Content Generated By  
                    GPT3  ''')
        st.write('[Try it :boom: ](https://chat.openai.com/chat/)')



st.write('- - -')
st.container()

a,b,c  = st.columns([1,2,1])
st.markdown('#')
with b:
    st.markdown("<h1 style='text-align: center; color: white ;'>Why Python ? </h1>", unsafe_allow_html=True)

col1, col2, col3 = st.columns(3)


with col1:
    with st.expander("**Data Science**", expanded=False):
        st.image("images\data.jpg", caption='Data is the Key')
        st.markdown('#')
        st.markdown('###')
        '---'
        st.write('''
        
  If you're specifically interested in using Python for data science, there are a few key areas you'll want to focus on. Firstly, it's important to have a strong foundation in Python programming concepts, such as variables, functions, loops, and data structures. Once you have that foundation, you can move on to exploring libraries and tools specifically designed for data analysis, such as NumPy, Pandas, Matplotlib, and Seaborn. These libraries allow you to efficiently manipulate, analyze, and visualize data, making them an essential part of the data science toolkit. Additionally, you should also familiarize yourself with machine learning techniques and algorithms, as these play a key role in data science and can be implemented using popular Python libraries such as scikit-learn. Remember, the best way to learn is by doing, so make sure to practice your skills by working on projects and participating in data science competitions.
        ''')


with col2:
    with st.expander("Web Development"):
        st.image("images\web.png",  caption= 'Build Powerful Apps' , use_column_width='always')
        '---'
        st.write('''
               If you're interested in using Python for web development, there are a few key frameworks and libraries you should become familiar with. Firstly, you'll want to have a solid understanding of the fundamentals of Python programming, as well as HTML, CSS, and JavaScript. Then, you can dive into popular Python web frameworks such as Django and Flask. These frameworks provide the building blocks you need to create dynamic, interactive websites and web applications. Additionally, you'll want to familiarize yourself with front-end technologies like JavaScript and CSS, as well as databases such as SQL and NoSQL, as these are often used in conjunction with Python for web development. Remember, practice makes perfect, so make sure to build projects and experiment with different tools and technologies to get a hands-on understanding of how everything fits together.

               ''')

with col3:
    with st.expander("AI / ML"):
        st.image("images\AIML.jpeg", caption= 'Unleashing the Power of Intelligence ', use_column_width='always')
        st.markdown('#')

        '---'

        st.write('''
        AI and ML are two important areas where Python is widely used. Python's ease of use and readability, as well as its extensive libraries and tools, make it an ideal choice for building and training AI and ML models.

In AI, Python is used for tasks such as natural language processing, computer vision, and robotics. Popular libraries for AI in Python include TensorFlow, Keras, and PyTorch, which allow developers to build and train complex models for a variety of tasks.

In ML, Python is used for tasks such as regression, classification, clustering, and reinforcement learning. The scikit-learn library is a popular choice for ML in Python, providing a range of algorithms for building and evaluating models.

To get started with AI and ML in Python, it's important to have a solid understanding of the Python programming language and basic statistics and linear algebra concepts. Additionally, practical experience is key, so it's important to build and experiment with models on real-world data.
        
        ''')



'---'